# Configuration for ALL environments is contained
# within this file.
# To specify an environment at runtime use the
# command line arg --spring.profiles.active=xxx (local, dev, qaA, qaB, prodA, etc.)
#

# Property declarations common to all environments

# Property overrides specific to an environment


spring:
  profiles:
    active: local
  main:
      web-environment: true
  data:
    mongodb:
      port: 27017
      host: 192.168.99.100
      database: aggregation

management:
  context-path: /rmm-metrics/
  port: 30813
  mainEngine:
    noResponseThresholdInMinutes: 2
endpoints:
  health:
    mapping:
      DOWN: INTERNAL_SERVER_ERROR
kafka:
  clientId:            aggregator-${spring.profiles.active}

server:
  port: 30010
