#refreshed !

# Configuration for ALL environments is contained
# within this file.
# To specify an environment at runtime use the
# command line arg --spring.profiles.active=xxx (local, dev, qaA, qaB, prodA, etc.)
#

# Property declarations common to all environments
spring:
  main:
    api-version: 1.0

  data:
    mongodb:
      host:         192.168.99.100
      port: 27017
      database: risk
      test: aaaa
